[usp_tester]
schema = "report"
logging_level = "verbose" # "verbose" or "errors_only" or "summary"

[usp_tester.defaults]
start_date = "2024-01-01"
end_date = "2024-01-31"
start_datetime = "2023-01-01 00:00:00"
end_datetime = "2023-01-31 23:59:59"
integer = 100
bit = 1
decimal = 0.0
varchar = "12345"
